version: '3.8'

services:
  vite-app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Useful for hot reload in Docker
    command: ["npm", "run", "dev", "--", "--host"]
